import type { NextPage } from 'next'
import * as React from "react"

import Head from 'next/head'
import Image from 'next/image'
import styles from './styles/Home.module.css'


import {
  ChakraProvider,
  Box,
  Text,
  Link,
  VStack,
  Code,
  Grid,
  theme,
  Heading,
} from "@chakra-ui/react"
import  ColorModeSwitcher  from "./ColorModeSwitcher"

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>React-test</title>
        <meta name="description" content="Generated by nayarawatanuki" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ChakraProvider theme={theme}>
          <Box alignSelf="flex-end">
            <ColorModeSwitcher />
          </Box>

          <Box textAlign="center" fontSize="xl">
            <Heading as='h2' size='3xl' noOfLines={1}>
              Bem-vindo(a)!
            </Heading>

            <Grid minH="100vh" p={3}>
              <Text as="sub">Clique no link abaixo para visualizar os formulários:</Text>
              <VStack spacing={8}>
                <Link
                  color="telegram.400"
                  href="/forms"
                  fontSize="4xl"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Formulários
                </Link>
              </VStack>
            </Grid>
          </Box>
        </ChakraProvider>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/nayarawatanuki"
          target="_blank"
          rel="noopener noreferrer"
        >
          CatFact Project by {'nayarawatanuki'}
          <span className={styles.logo}>
            <Image src="" alt="" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
